config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :posts do 
    resources :post_attachments
  end
  resources :post_attachments

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	mount_uploader :pict, AvatarUploader
	has_many :post_attachments
   accepts_nested_attributes_for :post_attachments

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	mount_uploader :picture, AvatarUploader
   belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :avatar) }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email,:current_password , :password, :password_confirmation, :avatar) }
end
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params.merge(:post_id => @post.id))
   respond_to do |format|
     if @post.save
      unless params[:post_attachments].nil?
       params[:post_attachments]['picture'].each do |a|
          @post_attachment = @post.post_attachments.create!(:picture => a, :post_id => @post.id)
       end
     else format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :ok, location: @post }
     end
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
def update
  respond_to do |format|
    if @post_attachment.update(post_attachment_params)
      format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
    end 
  end
end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :picture)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_autor, only: [:edit, :destroy, :update]
  # GET /posts
  # GET /posts.json

  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
       @post_attachments = @post.post_attachments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
       @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
def create
  @post = Post.new(post_params.merge(:user_id => current_user.id))

  respond_to do |format|
    if @post.save
      unless params[:post_attachments].nil?
      params[:post_attachments]['picture'].each do |a|
         @post_attachment = @post.post_attachments.create!(:picture => a, :post_id => @post.id)
       end
      end
      format.html { redirect_to @post, notice: 'Post was successfully created.' }
    else
      format.html { render action: 'new' }
    end
  end
end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, :role, :user_id,post_attachments_attributes: [:id, :post_id, :picture])
    end


    def check_autor
      if @post.user_id === current_user.id || current_user.role === 1
        true
      else
        redirect_to :root , alert: "Tu ne peux pas modifier cet article"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
   { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
 end

 def flash_messages(opts = {})
   flash.each do |msg_type, message|
     concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
              concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                       concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                       concat content_tag(:span, 'Close', class: 'sr-only')
              end)
              concat message
     end)
   end
   nil
 end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puuser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "main" %>
  <%= stylesheet_link_tag "materialize" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
</head>
<body>

<!-- Navbar -->
	<nav id="mainmenu" class="navbar navbar-default navbar-fixed-top navbar-burger" role="navigation">
		<div id="containeracc" class="container">
			<div class="navbar-header">
				<button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#monmenu">
					MENU
				</button>
				<a href="home" class="navbar-brand"><img id="logo1" src="/img/Logo-Roubaix-gray.png"></a>
			</div>
			<div class="collapse navbar-collapse navbar-right" id="monmenu">
				<ul id="ul" class="nav navbar-nav">
					<li><a href="home">Accueil</a></li>
					<li><a href="general">Simplon.co</a></li>
					<li><a href="adep">ADEP</a></li>
					<li><a href="contact">Contact</a></li>
					<% if user_signed_in? %>
					<li><%= link_to 'Edit profile', edit_user_registration_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
					<li id="Loggin">
						Connecté en tant que <strong><%= current_user.username %><%=image_tag(current_user.avatar, class: "img-circle",style: "width:30px; height:30px;")if current_user.avatar? %></strong></li>
						<% else %>
						<li><%= link_to "Sign up", new_user_registration_path %></li>
						<li><%= link_to "Login", new_user_session_path %></li>
						<% end %>
					</div>
					<% flash.each do |name, msg| %>
					<% end %>
				</div>
			</ul>
			</div>
		</div>
	</nav>

<!-- Navbar -->

<%= yield %>
<!-- ////////////////////   FOOTER   ///////////////////// -->
<footer>
	<div class="row">
		<div class="row">
		<div id="icon" class="col-md-5 col-md-offset-2">
    <div><img id="logobot" src="/img/Logo-Roubaix-blanc.png"></div>
				<a id="icongoogle" href="#"><i class="fa fa-google-plus-square"></i></a>
				<a id="iconyoutube" href="#"><i class="fa fa-youtube-square"></i></a>
				<a id="iconfacebook" href="#"><i class="fa fa-facebook-square"></i></a>
				<a id="icontwitter" href="#"><i class="fa fa-twitter-square"></i></a>
				<a id="iconinstagram" href="#"><i class="fa fa-instagram"></i></a>
			</div>
			<div id="sitemap" class="col-md-5">
				<div class="col-md-4 col-md-offset-0 col-sm-offset-0 col-xs-offset-0 paddingbot">
					<h2>Liens utiles</h2>
					<ul>
						<a href="#"><li>Adep</li></a>
						<a href="#"><li>Simplon</li></a>
						<a href="#"><li>OVH</li></a>
						<a href="#"><li>Roubaix</li></a>
					</ul>
				</div>
				<div class="col-md-4 col-md-offset-0 col-sm-offset-0 col-xs-offset-0 paddingbot">
					<h2>Contact</h2>
					<ul>
						<a href="#"><li>Thierry</li></a>
						<a href="#"><li>Othman</li></a>
						<a href="#"><li>Alexis</li></a>
						<a href="#"><li>Sabrina</li></a>
						<a href="#"><li>Damien</li></a>
					</ul>
				</div>
			</div>
		</div>
	</div>
  <div><hr>
<a class="btn modal-trigger" href="#modal1"><p>© 2015 Simplon.</p></a>
  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modalité générale</h4>
      <p>
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><p>J'accepte</p></a>
    </div>
  </div>
</div>
</footer>
	<div class="message flashh"> <%= flash_messages %></div>
</body>
</html>

app/views/post_attachments/_form.html.erb
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<h1>Listing Post Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.picture %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @post_attachment.picture %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>

app/views/posts/_form.html.erb
<header><%= form_for(@post, :html => { :multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <%= f.fields_for :post_attachments do |p| %>
     <div class="field">
       <%= p.label :picture %><br>
       <%= p.file_field :picture, :multiple => true ,name: "post_attachments[picture][]"%>
     </div>
   <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</header>

app/views/posts/edit.html.erb
<header><h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</header>

app/views/posts/index.html.erb
    <header>
      <div class="slider">
    <ul class="slides">
      <li>
        <img src="/img/Simplon-Roubaix-11.jpg"> <!-- random image -->
      </li>
      <li>
        <img src="/img/la_deuxieme.png"> <!-- random image -->
      </li>
      <li>
        <img src="/img/photo1.jpg"> <!-- random image -->
      </li>
    </ul>
  </div>
    </header>

<h1>Simplon</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.content %></td>
        <td><%= User.find(post.user_id).username if post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <% if (user_signed_in? &&current_user.id == post.user_id) || (user_signed_in? && current_user.admin == 1 ) %>
        <td><%= link_to 'Edit', edit_post_path(post)%></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<header><h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</header>

app/views/posts/show.html.erb
<header>
<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
  <%= image_tag(@post.pict , style: "width:90px; heigth:90px;") %>
</p>
<% @post_attachments.each do |p| %>
  <%= image_tag p.picture_url %>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</header>